[project]
name = "LLM2Seq"
version = "0.1.0"
description = "Vietnamese Abstractive Summarization Project"
requires-python = ">=3.9"

[tool.ruff]
line-length = 120
target-version = "py39"

exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "node_modules",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "tmp",
    "outputs",
    "runs"
]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501", "E741", "E701", "F841", "F401", "E402"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.pytest.ini_options]
python_files = ["test_*.py"]
