apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm2seq
  namespace: llm2seq
spec:
  rules:
    - host: llm2seq.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
