"""Evaluate JSONL predictions with the official Perl ROUGE-1.5.5 backend."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import unicodedata
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Any

from pyrouge import Rouge155

_SENTENCE_BOUNDARY = re.compile(r"(?<=[.!?])\s+")
_WORK_DIR_MARKER = ".generated_by_evaluate_rouge"
_ROUGE_PROTOCOL = "-c 95 -2 -1 -U -r 1000 -n 4 -w 1.2 -a -m"


def _sentences(text: Any) -> list[str]:
    text = unicodedata.normalize("NFC", str(text))
    sentences: list[str] = []
    for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        sentences.extend(part.strip() for part in _SENTENCE_BOUNDARY.split(line.strip()) if part.strip())
    return sentences or [""]


def _reset_work_dir(work_dir: Path) -> None:
    if work_dir.exists():
        if not (work_dir / _WORK_DIR_MARKER).is_file():
            raise FileExistsError(f"Refusing to delete unrecognized directory: {work_dir}. Choose another --work-dir.")
        shutil.rmtree(work_dir)


def _references(value: Any) -> list[Any]:
    if isinstance(value, list):
        if not value:
            raise ValueError("Reference list cannot be empty")
        if len(value) > 26:
            raise ValueError("At most 26 references are supported per example")
        return value
    return [value]


def _prepare_data(
    predictions_file: Path,
    work_dir: Path,
    prediction_field: str,
    reference_field: str,
) -> int:
    _reset_work_dir(work_dir)
    system_dir = work_dir / "system"
    reference_dir = work_dir / "reference"
    system_dir.mkdir(parents=True)
    reference_dir.mkdir(parents=True)
    (work_dir / _WORK_DIR_MARKER).write_text(
        "Generated by src/rouge155/evaluate_rouge.py\n",
        encoding="utf-8",
    )

    count = 0
    with predictions_file.open("r", encoding="utf-8") as handle:
        for line_number, raw in enumerate(handle, start=1):
            if not raw.strip():
                continue
            try:
                row = json.loads(raw)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSONL at {predictions_file}:{line_number}") from exc
            if prediction_field not in row or reference_field not in row:
                raise ValueError(
                    f"Missing {prediction_field!r}/{reference_field!r} at {predictions_file}:{line_number}"
                )
            (system_dir / f"summary.{count}.txt").write_text(
                "\n".join(_sentences(row[prediction_field])) + "\n",
                encoding="utf-8",
            )
            for reference_index, reference in enumerate(_references(row[reference_field])):
                label = chr(ord("A") + reference_index)
                (reference_dir / f"summary.{label}.{count}.txt").write_text(
                    "\n".join(_sentences(reference)) + "\n",
                    encoding="utf-8",
                )
            count += 1
    if count == 0:
        raise ValueError(f"No examples found in {predictions_file}")
    return count


def _pyrouge_version() -> str:
    try:
        return version("pyrouge")
    except PackageNotFoundError:
        return "unknown"


def evaluate(
    predictions_file: Path,
    work_dir: Path,
    output_file: Path,
    prediction_field: str = "prediction",
    reference_field: str = "reference",
) -> dict[str, Any]:
    predictions_file = predictions_file.expanduser().resolve()
    work_dir = work_dir.expanduser().resolve()
    output_file = output_file.expanduser().resolve()
    if not predictions_file.is_file():
        raise FileNotFoundError(f"Predictions JSONL not found: {predictions_file}")

    count = _prepare_data(
        predictions_file,
        work_dir,
        prediction_field,
        reference_field,
    )
    default_home = Path(__file__).resolve().parent / ".runtime/pyrouge-source/tools/ROUGE-1.5.5"
    rouge_home = Path(os.environ.get("PYROUGE_HOME_DIR", default_home)).resolve()
    rouge_script = rouge_home / "ROUGE-1.5.5.pl"
    if not rouge_script.is_file():
        raise FileNotFoundError(f"ROUGE-1.5.5.pl not found at {rouge_script}; set PYROUGE_HOME_DIR")
    if not os.access(rouge_script, os.X_OK):
        raise PermissionError(f"ROUGE script is not executable: chmod +x {rouge_script}")
    wordnet_database = rouge_home / "data/WordNet-2.0.exc.db"
    if not wordnet_database.exists():
        raise FileNotFoundError(f"WordNet-2.0 exception database not found: {wordnet_database}")

    local_perl = Path(__file__).resolve().parent / ".runtime/perl5/lib/perl5"
    if local_perl.is_dir():
        current = os.environ.get("PERL5LIB", "")
        os.environ["PERL5LIB"] = f"{local_perl}{os.pathsep}{current}" if current else str(local_perl)

    # Keep the constructor compatible with both the older pyrouge package
    # commonly installed on servers and the newer GitHub wrapper.
    rouge = Rouge155(str(rouge_home))
    rouge.system_dir = str(work_dir / "system")
    rouge.model_dir = str(work_dir / "reference")
    rouge.system_filename_pattern = r"summary\.(\d+)\.txt"
    rouge.model_filename_pattern = r"summary\.[A-Z]\.#ID#\.txt"

    # Deliberately use PyRouge defaults, matching Rouge155.convert_and_evaluate().
    # This wrapper appends -m before the config path, so Porter stemming and
    # the WordNet-2.0 exception database are enabled.
    raw_output = rouge.convert_and_evaluate()
    raw_scores = rouge.output_to_dict(raw_output)
    result = {
        "rouge1": raw_scores["rouge_1_f_score"] * 100.0,
        "rouge2": raw_scores["rouge_2_f_score"] * 100.0,
        "rougeL": raw_scores["rouge_l_f_score"] * 100.0,
        "num_examples": count,
        "backend": f"Perl ROUGE-1.5.5 via pyrouge=={_pyrouge_version()}",
        "stemming": True,
        "pyrouge_default_args": _ROUGE_PROTOCOL,
        "prediction_field": prediction_field,
        "reference_field": reference_field,
        "predictions_file": str(predictions_file),
        "prepared_data_dir": str(work_dir),
        "rouge_home": str(rouge_home),
        "raw_scores": raw_scores,
    }
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    output_file.with_suffix(".raw.txt").write_text(raw_output, encoding="utf-8")
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Calculate ROUGE-1/2/L F1 with official Perl ROUGE-1.5.5. "
            "The input must be JSONL with prediction and reference fields."
        )
    )
    parser.add_argument("predictions", type=Path, help="Prediction JSONL file")
    parser.add_argument("--work-dir", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--prediction-field", default="prediction")
    parser.add_argument("--reference-field", default="reference")
    args = parser.parse_args()
    predictions = args.predictions.expanduser().resolve()
    work_dir = args.work_dir or predictions.with_suffix(".rouge_data")
    output = args.output or predictions.with_suffix(".rouge155.json")
    result = evaluate(
        predictions,
        work_dir,
        output,
        args.prediction_field,
        args.reference_field,
    )
    print(f"ROUGE-1={result['rouge1']:.3f} ROUGE-2={result['rouge2']:.3f} ROUGE-L={result['rougeL']:.3f}")
    print(f"Saved metrics: {output.resolve()}")
    print(f"Saved raw output: {output.resolve().with_suffix('.raw.txt')}")


if __name__ == "__main__":
    main()
