name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Install Ruff
      run: pip install ruff
    - name: Run Ruff Linter
      run: ruff check .
    - name: Run Ruff Formatter Check
      run: ruff format --check .

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run oxlint
      uses: oxc-project/oxlint-action@v1
      with:
        working-directory: App/frontend
